apiVersion: v1
kind: Service
metadata:
  name: smart-talk-agent
  namespace: smart-talk
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: smart-talk-agent
  ports:
    - name: websocket
      protocol: TCP
      port: 8765
      targetPort: 8765
